# Site settings
title: Keble UIPrototype
email: thaddeus.renderwell@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Keble UIPrototype
baseurl: "/keble.uiprototype" # the subpath of your site, e.g. /blog
url: "http://renderwell.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
exclude:
- bower.json
- bower_components
- node_modules
- Gruntfile.js
- Makefile
- package.json
- README.md
